callback_url: http://sanduicheck.in/foursquare_callback
client_id: xxxxxxxxxx
client_secret: xxxxxxxxxx
access_token_url: https://foursquare.com/oauth2/access_token
auth_url: https://foursquare.com/oauth2/authorize